### PR TITLE
DEV Pipeline

### PR DESCRIPTION
**Pull request by alalvi00**
## Overview/Summary

Created a dev pipeline to be triggered upon release. Right now it will be triggered upon push to main for testing purposes

## This PR fixes/adds/changes/removes

1. *Replace me*
2. *Replace me*
3. *Replace me*

### Breaking Changes

1. *Replace me*
2. *Replace me*

## Testing Evidence

Please provide any testing evidence to show that your Pull Request works/fixes as described and planned (include screenshots, if appropriate).

## As part of this Pull Request I have

- [x] Checked for duplicate [Pull Requests](https://github.com/ssc-spc-ccoe-cei/azure-guardrails-solution-accelerator/pulls)
- [x] Associated it with relevant [GitHub Issues](https://github.com/ssc-spc-ccoe-cei/azure-guardrails-solution-accelerator/issues)
- [x] Ensured my code/branch is up-to-date with the latest changes in the `main` [branch](https://github.com/ssc-spc-ccoe-cei/azure-guardrails-solution-accelerator/tree/main)
- [x] Performed testing and provided evidence.
- [x] Updated relevant and associated documentation.
- [x] Ensure PowerShell module versions have been updated (manually or with the ./tools/Update-ModuleVersions.ps1 script)

### CODE REVIEW

**Comment by alalvi00** [comment]
#103

**Review by dutt0 — APPROVED** [review]
It seems that the workflow using push to main branch for workflow testing for now. Approving now so you can test and later update PR with release tag and re-request review. Thanks.

**Review by dutt0 — COMMENTED** [review]
Code triggers on 'push' to a branch. Please update it to tag release.

**Comment by alalvi00** [comment]
> Code triggers on 'push' to a branch. Please update it to tag release.

Yes once it redploy dev env on main branch, I will change it to be triggered on release with a new pr

**Review by dutt0 — APPROVED** [review]

**Review by nadersip — APPROVED** [review]

**Pull request merged**
