### PR TITLE
[Bug fix] Updated the GA MFA Control for GR1

### PR DESCRIPTION
**Pull request by alalvi00**
## Overview/Summary

Updated the GA MFA Control for GR1 covering multiple test scenarios. 

- Handles the txt file with empty new lines
- Gets rid of any unwarranted empty characters in the txt file
- Removes any UPNs from txt file that don't have a valid email format

## This PR fixes/adds/changes/removes

1. *Replace me*
2. *Replace me*
3. *Replace me*

### Breaking Changes

1. *Replace me*
2. *Replace me*

## Testing Evidence

Please provide any testing evidence to show that your Pull Request works/fixes as described and planned (include screenshots, if appropriate).

## As part of this Pull Request I have

- [x] Checked for duplicate [Pull Requests](https://github.com/ssc-spc-ccoe-cei/azure-guardrails-solution-accelerator/pulls)
- [x] Associated it with relevant [GitHub Issues](https://github.com/ssc-spc-ccoe-cei/azure-guardrails-solution-accelerator/issues)
- [x] Ensured my code/branch is up-to-date with the latest changes in the `main` [branch](https://github.com/ssc-spc-ccoe-cei/azure-guardrails-solution-accelerator/tree/main)
- [x] Performed testing and provided evidence.
- [x] Updated relevant and associated documentation.
- [x] Ensure PowerShell module versions have been updated (manually or with the ./tools/Update-ModuleVersions.ps1 script)

### CODE REVIEW

**Comment by alalvi00** [comment]
#65

**Review by dutt0 — COMMENTED** [review]
Please include the psmodules version update in the PR.

**Comment by alalvi00** [comment]
@singhgss we should have the debug set to off since we don't want to display debug messages to our client

**Review by singhgss — APPROVED** [review]

**Review by dutt0 — APPROVED** [review]
Looks good. Thank you @singhgss @alalvi00

**Pull request merged**
